### ISSUE TITLE
Support direct file names

### ISSUE THREAD

**Issue by mludvig** [ArjenSchwarz/fog#1]
Hi Arjen, I started using Fog and it's really convenient. However one thing is quite counterintuitive - it expects all the files in specific directories. Any chance to check if the given argument is an existing filename and if it is use it right away? And only if not try to find it under `templates/` or wherever?

For example:
```
# template.yml exists in the current dir -> use it
fog -f template.yml -n stack-name
```

The same for parameter files, tags, etc. If the given argument is a file use it and don't look elsewhere. Otherwise it's quite confusing - I give it a file and it says it can't find it.

Thanks!

**Comment by ArjenSchwarz** [comment]
Hi Michael, that's a good point and I've been meaning to add some functionality around this. Would the following work for you?
1. check if file exists in current directory
2. check if file exists in defined templates/tags/parameters directory
3. check if file exists in defined templates/tags/parameters directory

In the meantime as a workaround you could create a global fog.yaml (or your preferred syntax) in your homedir that includes
```yaml
templates:
  directory: .
tags:
  directory: .
parameters:
  directory: .
```

I think that should work until I've implemented this, although it might still complain as it doesn't expect an extension in the provided argument for the template. I have that on my list of things to fix (basically step 2 in the above list), but haven't gotten around to it yet.

**Comment by mludvig** [comment]
IMO Fog should check if the -f argument is a file or not, just like that even if it's not in the current directory. 

Assuming I run `fog -f /some/path/template.yml -n xxx` then in `ReadTemplate()` the `templateName` is `/some/path/template.yml` then before you loop over the extensions etc simply check with `os.Stat(templateName)` if it's an actual file name. If it is job done and you can read it immediately, if not loop through the extensions. The same in `ReadTagsfile()` and in `ReadParametersFile()`.

I'm not a big fan of any auto-detection magic, it's often confusing. If I give it a _file_ I mean to use _file_, not _templateDir + file + oneOfTheExtensionsInWhoKnowsWhatOrder_ ;)

**Comment by ArjenSchwarz** [comment]
After almost a year I've actually merged your PR. Sorry for the long wait, I was originally not planning to merge it as it was but finally decided it should just be included when I was doing some cleanup.
